[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow_donate = "4Rpr3wujcbhs7SRm7PYX9BHNcQmkss57UQfyZA36qDAf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/konstantina/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
