[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault_a = "7kmwXzTrcastwLt1HrVEMAgptFFnvcNCsCixHMShpcus"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/konstantina/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
