[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "8dKPLDbUaXSQs9gZzHLfMTushqChyY7AnUx2FQgzpa97"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/konstantina/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
